### PR TITLE
Laravel update

### PR DESCRIPTION
**Pull request by lukasyelle**
This PR updates Laratrade/Trader to support Laravel 5 - 7.

### CODE REVIEW

**Comment by lukasyelle** [comment]
@nasyrov Sorry for the new PR, the old one wasn't taking my new commit.

**Comment by lukasyelle** [comment]
@nasyrov Do you need anything else from me to get this merged?

**Comment by lukasyelle** [comment]
@nasyrov Let me know if so.

**Comment by lukasyelle** [comment]
Bump. @nasyrov Hope you're doing well. If you can no longer maintain this package I'd be willing to take over! Let me know.

**Comment by nasyrov** [comment]
Hi @lukasyelle,

Sorry just saw it, I'm going to merge it now.

**Pull request merged**
