### PR TITLE
fix #10

### LINKED ISSUE #10: Support for Laravel 8
Hi, can you please make it compatible with Laravel 8?

### PR DESCRIPTION
**Pull request by CrazyBoy49z**

### CODE REVIEW

**Comment by palentir** [comment]
I made the change in my json but I still can't seem to install it with composer. I get errors still:
 - laratrade/trader 1.0.2 requires illuminate/support ^5.5|^6.0|^7.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.51).

**Comment by CrazyBoy49z** [comment]
> I made the change in my json but I still can't seem to install it with composer. I get errors still:
> 
> * laratrade/trader 1.0.2 requires illuminate/support ^5.5|^6.0|^7.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.51).

This PR is not accepted so it cannot conflict 

https://packagist.org/packages/laratrade/trader 
image

**Comment by CrazyBoy49z** [comment]
@nasyrov

**Comment by nasyrov** [comment]
@CrazyBoy49z looks good to me, have you test it locally?

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z looks good to me, have you test it locally?

Yes, of course. Your code work in laravel 8+ but not installed from composer

**Comment by nasyrov** [comment]
@CrazyBoy49z merged and tagged a new release, enjoy!

**Pull request merged**
