### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by SiteBooster**
Make available in Laravel 5.7

### CODE REVIEW

**Review by TanvirAlam — APPROVED** [review]

**Review by TanvirAlam — APPROVED** [review]

**Comment by TanvirAlam** [comment]
@liacmedia Please merge this, I am in need of this

**Review by tijnhendrikson — APPROVED** [review]

**Comment by tijnhendrikson** [comment]
We have to wait for Scrutinizer to finish

**Comment by TanvirAlam** [comment]
@nasyrov would it be possible to merge this so it supports 5.7? thank you

**Comment by nasyrov** [comment]
@liacmedia done, thank you for PR!

**Pull request merged**
